// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MyDb.Models.EF;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MIS_StoList> MIS_StoLists { get; set; }

    public virtual DbSet<RelGroupAuth> RelGroupAuths { get; set; }

    public virtual DbSet<RelUserGroup> RelUserGroups { get; set; }

    public virtual DbSet<SysAuthList> SysAuthLists { get; set; }

    public virtual DbSet<SysGroup> SysGroups { get; set; }

    public virtual DbSet<SysUser> SysUsers { get; set; }

    public virtual DbSet<SysUser_View> SysUser_Views { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MIS_StoList>(entity =>
        {
            entity.ToTable("MIS_StoList");

            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.UploadDate).IsRequired();
        });

        modelBuilder.Entity<RelGroupAuth>(entity =>
        {
            entity.ToTable("RelGroupAuth");
        });

        modelBuilder.Entity<RelUserGroup>(entity =>
        {
            entity.ToTable("RelUserGroup");
        });

        modelBuilder.Entity<SysAuthList>(entity =>
        {
            entity.ToTable("SysAuthList");

            entity.Property(e => e.AuthCode).IsRequired();
        });

        modelBuilder.Entity<SysGroup>(entity =>
        {
            entity.ToTable("SysGroup");
        });

        modelBuilder.Entity<SysUser>(entity =>
        {
            entity.ToTable("SysUser");
        });

        modelBuilder.Entity<SysUser_View>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SysUser_View");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}