// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDb.Models.EF;

public partial class RelUserGroup
{
    public int id { get; set; }

    public int UserID { get; set; }

    public int GroupID { get; set; }
}