// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDb.Models.EF;

public partial class SysAuthList
{
    public int id { get; set; }

    public int pid { get; set; }

    public string AuthCode { get; set; }

    public string AuthType { get; set; }

    public string AuthName { get; set; }
}