// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDb.Models.EF;

public partial class SysGroup
{
    public int id { get; set; }

    public string GroupName { get; set; }
}