// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyDb.Models.EF;

public partial class SysUser
{
    public int id { get; set; }

    public string Acc { get; set; }

    public string Pwd { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }
}